name: 'Setup Nix'
description: 'Install Nix'
runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ github.token }}
